name: "Check for MAS updates and build Docker image"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: master

      - name: "Get latest MAS release"
        id: "mas-release"
        run: |
          echo "::set-output name=release::$(curl -sL "https://api.github.com/repos/monika-after-story/monikamoddev/releases/latest" | \
            perl -lne 'print $1 if /"tag_name": "([^"]+)"/')"

      - name: "Check if package already exists"
        id: "package-exists"
        env:
          MAS_RELEASE: "${{ steps.mas-release.outputs.release }}"
        run: |
          ./check-image-exists.sh

      - name: "Set up Docker Buildx"
        if: "steps.package-exists.outputs.exists == 'false'"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to GitHub Container Registry"
        if: "steps.package-exists.outputs.exists == 'false'"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Login to DockerHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          username: "dreamscached"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: "Build Docker image"
        if: "steps.package-exists.outputs.exists == 'false'"
        uses: docker/build-push-action@v2
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          file: "Dockerfile"
          tags: |
            ghcr.io/friends-of-monika/mas-mdk:latest,
            ghcr.io/friends-of-monika/mas-mdk:master,
            ghcr.io/friends-of-monika/mas-mdk:${{ steps.mas-release.outputs.release }},
            friendsofmonika/mas-mdk:latest,
            friendsofmonika/mas-mdk:master,
            friendsofmonika/mas-mdk:${{ steps.mas-release.outputs.release }}
          context: .
          build-args: "MAS_RELEASE=${{ steps.mas-release.outputs.release }}"
          push: true