name: "Build Docker image on push"
on:
  push:
    branch: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: master

      - name: "Get latest MAS release"
        id: "mas-release"
        run: |
          echo "::set-output name=release::$(curl -sL "https://api.github.com/repos/monika-after-story/monikamoddev/releases/latest" | \
            perl -lne 'print $1 if /"tag_name": "([^"]+)"/')"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          file: "Dockerfile"
          tags: "ghcr.io/friends-of-monika/mas-mdk:${{ steps.mas-release.outputs.release }},ghcr.io/friends-of-monika/mas-mdk:latest,ghcr.io/friends-of-monika/mas-mdk:master"
          context: .
          build-args: "MAS_RELEASE=${{ steps.mas-release.outputs.release }}"
          push: true